version: 2.1
orbs:
  node: circleci/node@4.0.0
workflows:
  tests:
    jobs:
      - prettier
      - test
jobs:
  prettier:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run prettier
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
